<a href="https://colab.research.google.com/github/interstellar146/assingment/blob/main/Lab_1_BAsics_of_Numpi_and_Panda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
##### Numpy Basics
import numpy as np    ### shift + enter

In [ ]:
np.__version__

'1.18.4'

In [ ]:
from platform import python_version
print(python_version())

3.6.9


In [ ]:
##### Create 1d array with numpy
list = [10,21,23,44,51]
a = np.array(list)
a

array([10, 21, 23, 44, 51])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
### Create 2d array
a = np.array([[12,4,5],[23,45,66],[45,34,23]])
a

array([[12,  4,  5],
       [23, 45, 66],
       [45, 34, 23]])

In [ ]:
a.ndim

2

In [ ]:
a.shape

(3, 3)

In [ ]:
a.size

9

In [ ]:
a.itemsize

8

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a

array([[12,  4,  5],
       [23, 45, 66],
       [45, 34, 23]])

In [ ]:
a[0]

array([12,  4,  5])

In [ ]:
a[2]

array([45, 34, 23])

In [ ]:
a[0:]

array([[12,  4,  5],
       [23, 45, 66],
       [45, 34, 23]])

In [ ]:
a[1:]

array([[23, 45, 66],
       [45, 34, 23]])

In [ ]:
a[:2]

array([[12,  4,  5],
       [23, 45, 66]])

In [ ]:
a[1,1]

45

In [ ]:
a[:,2]

array([ 5, 66, 23])

In [ ]:
#### Generate some equidistant numbers b/w some range
np.linspace(1,100,100)   #### (start,end,no.of samples)

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])

In [ ]:
####
a = np.arange(1,102,5)
a

array([  1,   6,  11,  16,  21,  26,  31,  36,  41,  46,  51,  56,  61,
        66,  71,  76,  81,  86,  91,  96, 101])

In [ ]:
a.min()

1

In [ ]:
a.max()

101

In [ ]:
a.mean()

51.0

In [ ]:
a.sum()

1071

In [ ]:
a.argmax()

20

In [ ]:
a.argmin()

0

In [ ]:
a

array([  1,   6,  11,  16,  21,  26,  31,  36,  41,  46,  51,  56,  61,
        66,  71,  76,  81,  86,  91,  96, 101])

In [ ]:
### Create 2d array
a = np.array([[12,4,5],[23,45,66],[45,34,23]])
a

array([[12,  4,  5],
       [23, 45, 66],
       [45, 34, 23]])

In [ ]:
a.sum()

257

In [ ]:
a.sum(axis=1) ###row wise sum

array([ 21, 134, 102])

In [ ]:
a.sum(axis=0) ### column wise sum

array([80, 83, 94])

In [ ]:
##### Concatination of arrays
a = np.array([[12,4,5],[23,45,66],[45,34,23]])
b = np.array([[1,40,50],[2,4,6],[4,3,2]])
##Vertical stacking
np.vstack((a,b))

array([[12,  4,  5],
       [23, 45, 66],
       [45, 34, 23],
       [ 1, 40, 50],
       [ 2,  4,  6],
       [ 4,  3,  2]])

In [ ]:
##Horizontal stacking
np.hstack((a,b))

array([[12,  4,  5,  1, 40, 50],
       [23, 45, 66,  2,  4,  6],
       [45, 34, 23,  4,  3,  2]])

In [ ]:
#### Zero matrix
zero = np.zeros(5)
zero

array([0., 0., 0., 0., 0.])

In [ ]:
zero = np.zeros((5,5))
zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
#### Ones matrix
ones = np.ones((5,5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
ones*10

array([[10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.]])

In [ ]:
ones.dtype

dtype('float64')

In [ ]:
ones.astype('int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
#### random Numbers
np.random.randint(10,100,20)

array([37, 56, 82, 16, 22, 42, 36, 61, 83, 62, 95, 84, 52, 32, 72, 62, 78,
       21, 90, 57])

In [ ]:
#### random Numbers
np.random.seed(2)
np.random.randint(10,100,20)

array([50, 25, 82, 32, 53, 92, 85, 17, 44, 59, 85, 95, 57, 73, 41, 30, 47,
       49, 77, 14])

In [ ]:
np.random.seed(3)
np.random.randint(10,100,(3,3))

array([[34, 13, 66],
       [82, 10, 31],
       [29, 84, 51]])

In [ ]:
np.random.seed(3)
a = np.random.randint(10,100,(3,4))
a

array([[34, 13, 66, 82],
       [10, 31, 29, 84],
       [51, 20, 31, 48]])

In [ ]:
a.shape

(3, 4)

In [ ]:
a.reshape(4,3)

array([[34, 13, 66],
       [82, 10, 31],
       [29, 84, 51],
       [20, 31, 48]])

In [ ]:
a.reshape(2,6)

array([[34, 13, 66, 82, 10, 31],
       [29, 84, 51, 20, 31, 48]])

In [ ]:
###### End of Numpy

In [ ]:
#### Pandas
#### Series  |||| DataFrame

In [ ]:
### Series
## 1. It converts the data into the sequential form
## 2. It is similar to an array but have index attached to it
## 3. It can hold data like list,tuple,array and dictionary

In [ ]:
import pandas as pd

In [ ]:
marks = [100,90,80,75,40]
s1 = pd.Series(marks)
s1

0    100
1     90
2     80
3     75
4     40
dtype: int64

In [ ]:
marks = [100,90,80,75,40]
subjects = ["Maths","Science","English","SST","EVS"]
s1 = pd.Series(marks,index=subjects)
s1

Maths      100
Science     90
English     80
SST         75
EVS         40
dtype: int64

In [ ]:
type(s1)

pandas.core.series.Series

In [ ]:
marks = [100,90,80,75,40]
subjects = ("Maths","Science","English","SST","EVS")
s1 = pd.Series(marks,index=subjects)
s1

Maths      100
Science     90
English     80
SST         75
EVS         40
dtype: int64

In [ ]:
dict = {"Maths":100,"Science":100,"IP":80,"Hindi":90,"SST":80}
s2 =  pd.Series(dict)
s2

Maths      100
Science    100
IP          80
Hindi       90
SST         80
dtype: int64

In [ ]:
s3 = s1 + s2

In [ ]:
s3

EVS          NaN
English      NaN
Hindi        NaN
IP           NaN
Maths      200.0
SST        155.0
Science    190.0
dtype: float64

In [ ]:
s3.mean()

181.66666666666666

In [ ]:
s3.sum()

545.0

In [ ]:
s3.sort_values()

SST        155.0
Science    190.0
Maths      200.0
EVS          NaN
English      NaN
Hindi        NaN
IP           NaN
dtype: float64

In [ ]:
s3.sort_values(ascending=False)

Maths      200.0
Science    190.0
SST        155.0
EVS          NaN
English      NaN
Hindi        NaN
IP           NaN
dtype: float64

In [ ]:
s3.sort_values(ascending=False,na_position="first")

EVS          NaN
English      NaN
Hindi        NaN
IP           NaN
Maths      200.0
Science    190.0
SST        155.0
dtype: float64

In [ ]:
#### DataFrame
### Collection of Series
df = pd.DataFrame(s3)
df

0
EVS        NaN
English    NaN
Hindi      NaN
IP         NaN
Maths    200.0
SST      155.0
Science  190.0

In [ ]:
df.head(2)

0
EVS     NaN
English NaN

In [ ]:
df.tail()

0
Hindi      NaN
IP         NaN
Maths    200.0
SST      155.0
Science  190.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7 entries, EVS to Science
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       3 non-null      float64
dtypes: float64(1)
memory usage: 432.0+ bytes


In [ ]:
df

0
EVS        NaN
English    NaN
Hindi      NaN
IP         NaN
Maths    200.0
SST      155.0
Science  190.0

In [ ]:
df['School Name'] = "DPS Delhi"
df

Marks School Name
EVS        NaN   DPS Delhi
English    NaN   DPS Delhi
Hindi      NaN   DPS Delhi
IP         NaN   DPS Delhi
Maths    200.0   DPS Delhi
SST      155.0   DPS Delhi
Science  190.0   DPS Delhi

In [ ]:
df.rename(columns={0:"Marks"},inplace=True)
df

Marks
EVS        NaN
English    NaN
Hindi      NaN
IP         NaN
Maths    200.0
SST      155.0
Science  190.0

In [ ]:
#df = df.reset_index()
df.reset_index(inplace=True)

In [ ]:
df

index  Marks School Name
0      EVS    NaN   DPS Delhi
1  English    NaN   DPS Delhi
2    Hindi    NaN   DPS Delhi
3       IP    NaN   DPS Delhi
4    Maths  200.0   DPS Delhi
5      SST  155.0   DPS Delhi
6  Science  190.0   DPS Delhi

In [ ]:
df.rename(columns={"index":"Subjects"},inplace=True)

In [ ]:
df

Subjects  Marks School Name
0      EVS    NaN   DPS Delhi
1  English    NaN   DPS Delhi
2    Hindi    NaN   DPS Delhi
3       IP    NaN   DPS Delhi
4    Maths  200.0   DPS Delhi
5      SST  155.0   DPS Delhi
6  Science  190.0   DPS Delhi

In [ ]:
#df.dropna(inplace=True)
df['Marks'].fillna(40,inplace=True)
df

Subjects  Marks School Name
0      EVS   40.0   DPS Delhi
1  English   40.0   DPS Delhi
2    Hindi   40.0   DPS Delhi
3       IP   40.0   DPS Delhi
4    Maths  200.0   DPS Delhi
5      SST  155.0   DPS Delhi
6  Science  190.0   DPS Delhi

In [ ]:
df['Marks']

0     40.0
1     40.0
2     40.0
3     40.0
4    200.0
5    155.0
6    190.0
Name: Marks, dtype: float64

In [ ]:
df[["Marks","School Name"]]

Marks School Name
0   40.0   DPS Delhi
1   40.0   DPS Delhi
2   40.0   DPS Delhi
3   40.0   DPS Delhi
4  200.0   DPS Delhi
5  155.0   DPS Delhi
6  190.0   DPS Delhi

In [ ]:
df.iloc[3]

Subjects              IP
Marks                 40
School Name    DPS Delhi
Name: 3, dtype: object

In [ ]:
df.iloc[1:5]

Subjects  Marks School Name
1  English   40.0   DPS Delhi
2    Hindi   40.0   DPS Delhi
3       IP   40.0   DPS Delhi
4    Maths  200.0   DPS Delhi

In [ ]:
df["Grade"] = ["E","E","E","E","A","B","A"]
df

Subjects  Marks School Name Grade
0      EVS   40.0   DPS Delhi     E
1  English   40.0   DPS Delhi     E
2    Hindi   40.0   DPS Delhi     E
3       IP   40.0   DPS Delhi     E
4    Maths  200.0   DPS Delhi     A
5      SST  155.0   DPS Delhi     B
6  Science  190.0   DPS Delhi     A

In [ ]:
new_df = pd.DataFrame()
new_df["Subjects"] = df["Subjects"]
new_df["Marks"] = df["Marks"]
new_df["Column 1"] = "Data"
new_df["School Name"] = df["School Name"]
new_df["Grade"] = df["Grade"]
new_df

Subjects  Marks Column 1 School Name Grade
0      EVS   40.0     Data   DPS Delhi     E
1  English   40.0     Data   DPS Delhi     E
2    Hindi   40.0     Data   DPS Delhi     E
3       IP   40.0     Data   DPS Delhi     E
4    Maths  200.0     Data   DPS Delhi     A
5      SST  155.0     Data   DPS Delhi     B
6  Science  190.0     Data   DPS Delhi     A

In [ ]:
data = "My Data"
df.insert(3,"New Column",data)
df

Subjects  Marks School Name New Column Grade
0      EVS   40.0   DPS Delhi    My Data     E
1  English   40.0   DPS Delhi    My Data     E
2    Hindi   40.0   DPS Delhi    My Data     E
3       IP   40.0   DPS Delhi    My Data     E
4    Maths  200.0   DPS Delhi    My Data     A
5      SST  155.0   DPS Delhi    My Data     B
6  Science  190.0   DPS Delhi    My Data     A

In [ ]:
df.drop(["New Column"],axis=1,inplace=True)  ### deleting the column

In [ ]:
df

Subjects  Marks School Name Grade
0      EVS   40.0   DPS Delhi     E
1  English   40.0   DPS Delhi     E
2    Hindi   40.0   DPS Delhi     E
3       IP   40.0   DPS Delhi     E
4    Maths  200.0   DPS Delhi     A
5      SST  155.0   DPS Delhi     B
6  Science  190.0   DPS Delhi     A

In [ ]:
df.drop([6],axis=0,inplace=True)  ### deleting the row
df

Subjects  Marks School Name Grade
0      EVS   40.0   DPS Delhi     E
1  English   40.0   DPS Delhi     E
2    Hindi   40.0   DPS Delhi     E
3       IP   40.0   DPS Delhi     E
4    Maths  200.0   DPS Delhi     A
5      SST  155.0   DPS Delhi     B

In [ ]:
new_df = df.copy()

In [ ]:
new_df

Subjects  Marks School Name Grade
0      EVS   40.0   DPS Delhi     E
1  English   40.0   DPS Delhi     E
2    Hindi   40.0   DPS Delhi     E
3       IP   40.0   DPS Delhi     E
4    Maths  200.0   DPS Delhi     A
5      SST  155.0   DPS Delhi     B

In [ ]:
df = df.append(new_df)
df

Subjects  Marks School Name Grade
0      EVS   40.0   DPS Delhi     E
1  English   40.0   DPS Delhi     E
2    Hindi   40.0   DPS Delhi     E
3       IP   40.0   DPS Delhi     E
4    Maths  200.0   DPS Delhi     A
5      SST  155.0   DPS Delhi     B
0      EVS   40.0   DPS Delhi     E
1  English   40.0   DPS Delhi     E
2    Hindi   40.0   DPS Delhi     E
3       IP   40.0   DPS Delhi     E
4    Maths  200.0   DPS Delhi     A
5      SST  155.0   DPS Delhi     B

In [ ]:
df.reset_index(inplace=True)
df

index Subjects  Marks School Name Grade
0       0      EVS   40.0   DPS Delhi     E
1       1  English   40.0   DPS Delhi     E
2       2    Hindi   40.0   DPS Delhi     E
3       3       IP   40.0   DPS Delhi     E
4       4    Maths  200.0   DPS Delhi     A
5       5      SST  155.0   DPS Delhi     B
6       0      EVS   40.0   DPS Delhi     E
7       1  English   40.0   DPS Delhi     E
8       2    Hindi   40.0   DPS Delhi     E
9       3       IP   40.0   DPS Delhi     E
10      4    Maths  200.0   DPS Delhi     A
11      5      SST  155.0   DPS Delhi     B

In [ ]:
df.drop_duplicates(inplace=True)    ### remove duplicate rows
df

index Subjects  Marks School Name Grade
0      0      EVS   40.0   DPS Delhi     E
1      1  English   40.0   DPS Delhi     E
2      2    Hindi   40.0   DPS Delhi     E
3      3       IP   40.0   DPS Delhi     E
4      4    Maths  200.0   DPS Delhi     A
5      5      SST  155.0   DPS Delhi     B